/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  videoEmbeddingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'video-embedding',
    },
  ],
  serverAPISidebar: [
    {
      type: 'autogenerated',
      dirName: 'server-api',
    },
  ],
  drmSidebar: [
    'drm-service/getting-started',
    {
      type: 'category',
      label: 'Encryption',
      items: [
        'drm-service/encryption/widevine-encryption',
        'drm-service/encryption/fairplay-encryption',
      ],
    },
    {
      type: 'category',
      label: 'Get license',
      items: [
        'drm-service/widevine-configuration',
        'drm-service/fairplay-configuration',
      ],
    },
    'drm-service/widevine-specs',
    'drm-service/drm-policies',
  ],
  transcodingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'transcoding-service',
    },
  ],
  mobileSdk: [
      {
        type: 'autogenerated',
        dirName: 'mobile-sdk',
      },
    ],
  liveStreamApi: [
      {
        type: 'autogenerated',
        dirName: 'live-stream-api',
      },
    ],
  uploaderSidebar: [
    {
      type: 'autogenerated',
      dirName: 'videos-uploader',
    },
  ],
  tpstorageSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tpstorage',
    },
  ],
};

module.exports = sidebars;
